# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Unicode-String
version:      2.09
version_from: String.pm
installdirs:  site
requires:
    MIME::Base64:                  2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
